# Generated by Django 5.0 on 2023-12-27 07:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team_two',
            field=models.ManyToManyField(blank=True, null=True, related_name='team_two', to=settings.AUTH_USER_MODEL),
        ),
    ]
