# Generated by Django 5.0 on 2023-12-30 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_uuid'),
        ('members', '0002_profile_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set',
            old_name='winner_score',
            new_name='team_one_score',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='loser_score',
            new_name='team_two_score',
        ),
        migrations.RemoveField(
            model_name='rally',
            name='rally_result',
        ),
        migrations.RemoveField(
            model_name='rally',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='rally',
            name='server',
        ),
        migrations.RemoveField(
            model_name='rally',
            name='shot',
        ),
        migrations.RemoveField(
            model_name='team',
            name='players',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_name',
        ),
        migrations.AddField(
            model_name='team',
            name='player_one',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teams_as_player_one', to='members.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='player_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams_as_player_two', to='members.profile'),
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_one',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_two',
        ),
        migrations.AddField(
            model_name='match',
            name='team_one',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team_one', to='matches.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='team_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team_two', to='matches.team'),
        ),
    ]
