# Generated by Django 4.1.7 on 2023-11-16 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('date', models.DateField()),
                ('player_limit', models.IntegerField()),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.location')),
            ],
        ),
        migrations.CreateModel(
            name='EventRsvp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsvp_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('rsvp', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
