# Generated by Django 4.2 on 2024-01-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_sessions', '0006_alter_sessionwaitlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrsvp',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
