# Generated by Django 4.2 on 2024-01-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_sessions', '0007_sessionrsvp_attended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionrsvp',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('other', 'Other')], default='cash', max_length=10, null=True),
        ),
    ]
