# Generated by Django 4.1.7 on 2023-12-26 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(default='', help_text='i.e. friendly/competitive, beginner/intermediate/advanced, etc.', max_length=255)),
                ('sport', models.CharField(choices=[('Badminton', 'Badminton'), ('Table Tennis', 'Table Tennis')], default='Badminton', max_length=128)),
                ('day', models.CharField(blank=True, choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], help_text='Which day of the week does your club usually play?', max_length=9)),
                ('time', models.TimeField(blank=True, default='20:00', help_text='What time does your session usually start?', null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('members_price', models.IntegerField(blank=True, help_text='If your club has a different price for members, add this here.', null=True)),
                ('rsvp_required', models.BooleanField(default=False, help_text='Do you require RSVPs to attend your sessions?')),
                ('contact', models.CharField(blank=True, help_text='Contact details for enquiries and RSVP.', max_length=255, null=True)),
                ('hidden', models.BooleanField(default=False, help_text='You can turn your club into a private club by hiding it from public view.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('favourited', models.ManyToManyField(blank=True, related_name='favourited', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(help_text="If you can't find your club's location, go to the Location page to add a new location first.", on_delete=django.db.models.deletion.PROTECT, to='locations.location')),
                ('organiser', models.ManyToManyField(related_name='organiser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
