# Generated by Django 5.0 on 2023-12-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='website',
            field=models.URLField(blank=True, help_text='If your club has a website, add it here.', null=True),
        ),
    ]
