# Generated by Django 5.0 on 2023-12-29 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_club_website'),
        ('locations', '0002_location_created_date_location_modified_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='location',
            field=models.ForeignKey(help_text="If you can't find your club's location, go to the Location page to add a new location first.", null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.location'),
        ),
    ]
