# Generated by Django 4.1.7 on 2023-12-17 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_description_alter_event_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventrsvp',
            old_name='rsvp_datetime',
            new_name='created_datetime',
        ),
        migrations.AddField(
            model_name='eventrsvp',
            name='updated_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
