# Generated by Django 5.0 on 2023-12-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default='2023-12-26'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
